# Generated by Django 4.0.6 on 2022-07-28 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('review', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
    ]
